application: buscallinghr
version: 1-0-0
runtime: python27
api_version: 1
threadsafe: true

skip_files:
# begin default skip_files
- ^(.*/)?(app|index)\.ya?ml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
# end default skip_files
- ^\.git/.*
- ^\.gitignore
- ^(.*/)?\.DS_Store

builtins:
- datastore_admin: on
- remote_api: on

libraries:
- name: jinja2
  version: latest
- name: markupsafe
  version: latest

handlers:
# shortcut for jquery :)
- url: /static/jquery.js
  static_files: static/js/jquery-1.6.1.min.js
  upload: static/js/jquery-1.6.1.min.js

- url: /static/(.*\.css)
  static_files: static/css/\1
  upload: static/css/(.*\.css)

- url: /static/(.*\.scss)
  static_files: static/scss/\1
  upload: static/scss/(.*\.scss)
  mime_type: text/scss

- url: /static/(.*\.js)
  static_files: static/js/\1
  upload: static/js/(.*\.js)

- url: /static/(.*\.coffee)
  static_files: static/coffee/\1
  upload: static/coffee/(.*\.coffee)
  mime_type: text/coffeescript

- url: /static/(.*\.(png|gif|jpg|jpeg))
  static_files: static/img/\1
  upload: static/img/(.*\.(png|gif|jpg|jpeg))

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /favicon\.(ico|png)
  static_files: static/img/favicon.png
  upload: static/img/favicon.png

- url: /tasks/.*
  script: main.app
  login: admin # secured for cron

- url: /.*
  script: main.app
