application: buscalling
version: 0-8-7
runtime: python
api_version: 1

handlers:
# shortcut for jquery :)
- url: /js/jquery.js
  static_files: static/js/jquery-1.6.1.min.js
  upload: static/js/jquery-1.6.1.min.js

- url: /js
  static_dir: static/js

- url: /css
  static_dir: static/css

- url: /img
  static_dir: static/img

- url: .*
  script: main.py
