application: buscalling
version: 0-8-9
runtime: python
api_version: 1

handlers:
# shortcut for jquery :)
- url: /js/jquery.js
  static_files: static/js/jquery-1.6.1.min.js
  upload: static/js/jquery-1.6.1.min.js

- url: /js
  static_dir: static/js

- url: /css
  static_dir: static/css

- url: /img
  static_dir: static/img

- url: /favicon.(ico|png)
  static_files: static/img/favicon.png
  upload: static/img/favicon.png
  # source: http://www.freeiconsweb.com/128x28_city_icons.html

- url: .*
  script: main.py
