application: buscalling
version: 0-9-1
runtime: python
api_version: 1

builtins:
- datastore_admin: on

handlers:
# shortcut for jquery :)
- url: /static/jquery.js
  static_files: static/js/jquery-1.6.1.min.js
  upload: static/js/jquery-1.6.1.min.js

- url: /static/(.*\.css)
  static_files: static/css/\1
  upload: static/css/(.*\.css)

- url: /static/(.*\.scss)
  static_files: static/scss/\1
  upload: static/scss/(.*\.scss)

- url: /static/(.*\.js)
  static_files: static/js/\1
  upload: static/js/(.*\.js)

- url: /static/(.*\.coffee)
  static_files: static/coffee/\1
  upload: static/coffee/(.*\.coffee)

- url: /static/(.*\.(png|jpg|jpeg))
  static_files: static/img/\1
  upload: /static/img/(.*\.(png|jpg|jpeg))

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /favicon\.(ico|png)
  static_files: static/img/favicon.png
  upload: static/img/favicon.png

- url: /tasks/.*
  script: main.py
  login: admin # secured for cron

- url: .*
  script: main.py
