application: buscalling
version: 0-9-1
runtime: python
api_version: 1

handlers:
# shortcut for jquery :)
- url: /js/jquery.js
  static_files: static/js/jquery-1.6.1.min.js
  upload: static/js/jquery-1.6.1.min.js

- url: /js
  static_dir: static/js

- url: /css
  static_dir: static/css

- url: /img
  static_dir: static/img

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /favicon.(ico|png)
  static_files: static/img/favicon.png
  upload: static/img/favicon.png
  # source: http://www.freeiconsweb.com/128x28_city_icons.html

- url: /tasks/.*
  script: main.py
  login: admin # secured for cron

- url: .*
  script: main.py
